version: "3.9"
services:
  test-db:
    image: postgres:16
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5432:5432"

  prod-db:
    image: postgres:16
    environment:
      POSTGRES_DB: prod
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_pass
    ports:
      - "5433:5432"
